name: Update Ontology

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Setup Robot
      run: sh utils/setup-robot.sh
    - name: Generate OWL file
      run: sh utils/convert-owl.sh # This will produce an output foldere: Use Node.js ${{ matrix.node-version }}
    - name: Save build output
      uses: actions/upload-artifact@v1
      with:
        name: built-output
        path: ./output

  deploy-site:
    runs-on: ubuntu-latest
    needs: build    
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Load saved build output
        uses: actions/download-artifact@v1
        with:
          name: built-output
          path: ./output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: output
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
